In [61]:
#https://machinelearningmastery.com/the-attention-mechanism-from-scratch/
import numpy as np
import scipy as sp

In [62]:
word_1 = np.array([1,0,0])
word_2 = np.array([0,1,0])
word_3 = np.array([1,1,0])
word_4 = np.array([0,0,1])

In [63]:
np.random.seed(42)
W_Q = np.random.randint(3, size=(3,3))
W_K = np.random.randint(3, size=(3,3))
W_V = np.random.randint(3, size=(3,3))

In [64]:
W_Q

array([[2, 0, 2],
       [2, 0, 0],
       [2, 1, 2]])

In [65]:
query_1 = word_1 @ W_Q
key_1 = word_1 @ W_K
value_1 = word_1 @ W_V

query_2 = word_2 @ W_Q
key_2 = word_2 @ W_K
value_2 = word_2 @ W_V

query_3 = word_3 @ W_Q
key_3 = word_3 @ W_K
value_3 = word_3 @ W_V

query_4 = word_4 @ W_Q
key_4 = word_4 @ W_K
value_4 = word_4 @ W_V

In [66]:
def softmax(y,axis=0):
    print(y)
    denom = np.sum(np.exp(y),axis=axis)
    return np.exp(y)/denom

In [67]:
scores_1 =np.array([
    np.dot(query_1,key_1),
    np.dot(query_1,key_2),
    np.dot(query_1,key_3),
    np.dot(query_1,key_4)
])
# print(key_1.shape[0])
scores_1 = scores_1/np.sqrt(key_1.shape[0])
attention_weights1 = softmax(scores_1)

[4.61880215 1.15470054 5.77350269 1.15470054]


In [68]:
attention_weights1

array([0.23608986, 0.00738988, 0.74913039, 0.00738988])

In [69]:
attention = attention_weights1[0]*value_1 + attention_weights1[1]*value_2 + attention_weights1[2]*value_3 + attention_weights1[3]*value_4

In [70]:
attention

array([0.98522025, 1.74174051, 0.75652026])

In [71]:
words = np.array([word_1,word_2,word_3,word_4])

In [72]:
Q = words @ W_Q
K = words @ W_K
V = words @ W_V


In [73]:
scores = Q @ K.transpose()

In [84]:
weights = sp.special.softmax(scores/K.shape[1]**0.5,axis=1)

In [85]:
print(K.shape[1])

3


In [86]:
attention = weights @ V

In [87]:
print(attention)

[[0.98522025 1.74174051 0.75652026]
 [0.90965265 1.40965265 0.5       ]
 [0.99851226 1.75849334 0.75998108]
 [0.99560386 1.90407309 0.90846923]]
